# convert a json into a DF

In [1]:
import pandas as pd

In [2]:
pd.read_json(r"C:\Users\Pranav Wadatkar\Desktop\Python\structured-learning\Gatthering data ML\train.json")

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

# Fetching data using API

In [3]:
import pandas as pd
import requests

In [4]:
account_id = "23858545"
url = f"https://api.themoviedb.org/3/account/{account_id}/rated/movies?language=en-US&page=1&sort_by=created_at.asc"
response = requests.get(url)

print(response.text)

{"status_code":7,"status_message":"Invalid API key: You must be granted a valid key.","success":false}

In [7]:
import requests

account_id = "23858545"

url = f"https://api.themoviedb.org/3/account/{account_id}/rated/movies"

params = {
    "language": "en-US",
    "page": 1,
    "sort_by": "created_at.asc"
}

headers = {
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI2NDM0MTM2OTUyNWJkYTlmYTU5MDgwMzdhOTliOGYyYiIsIm5iZiI6MTc5MDkyNzgzMi4wOSwic3ViIjoiNmFiZjYzZDg1YzRkNDFhMzFjYjA5MjRmIiwic2NvcGVzIjpbImFwaV9yZWFkIl0sInZlcnNpb24iOjF9.DyXqznHZk_k4P91Jxoi4gsp1JUHVz2cNbM78csRbFvw",
    "accept": "application/json"
}

response = requests.get(
    url,
    params=params,
    headers=headers
)

print(response.status_code)
result = response.text
result

200

'{"page":1,"results":[],"total_pages":0,"total_results":0}'

In [13]:
access_token = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI2NDM0MTM2OTUyNWJkYTlmYTU5MDgwMzdhOTliOGYyYiIsIm5iZiI6MTc5MDkyNzgzMi4wOSwic3ViIjoiNmFiZjYzZDg1YzRkNDFhMzFjYjA5MjRmIiwic2NvcGVzIjpbImFwaV9yZWFkIl0sInZlcnNpb24iOjF9.DyXqznHZk_k4P91Jxoi4gsp1JUHVz2cNbM78csRbFvw"

def get_top_tmdb_movies(access_token, pages):

    url = "https://api.themoviedb.org/3/discover/movie"

    headers = {
        "Authorization": f"Bearer {access_token}",
        "accept": "application/json"
    }

    movies = []

    for page in range(1, pages + 1):

        params = {
            "language": "en-US",
            "page": page,
            "sort_by": "vote_average.desc",
            "vote_count.gte": 1000
        }

        response = requests.get(
            url,
            params=params,
            headers=headers
        )

        response.raise_for_status()

        data = response.json()
        movies.extend(data["results"])

    return movies

In [ ]:
movies = get_top_tmdb_movies(access_token, 3)

# for movie in movies:
#     print(
#         f"{movie['title']} | "
#         f"{movie['vote_average']}/10 | "
#         f"{movie['vote_count']} votes"
#     )

df = pd.DataFrame(movies)

,title,release_date,vote_average,vote_count
0,Avatar Aang: The Last Airbender,2026-07-24,9.149,1235
1,Swapped,2026-05-01,8.866,2219
2,Demon Slayer: Kimetsu no Yaiba Infinity Castle,2025-07-18,8.796,2225
3,The Shawshank Redemption,1994-09-23,8.731,31473
4,The Godfather,1972-03-14,8.688,23675
5,Project Hail Mary,2026-03-15,8.642,8088
6,Michael,2026-04-22,8.625,4459
7,12 Angry Men,1957-04-10,8.574,10424
8,The Godfather Part II,1974-12-20,8.573,14401
9,Schindler's List,1993-12-15,8.569,17982

In [18]:
df[["title", "release_date", "vote_average", "vote_count"]].head(10)

,title,release_date,vote_average,vote_count
0,Avatar Aang: The Last Airbender,2026-07-24,9.149,1235
1,Swapped,2026-05-01,8.866,2219
2,Demon Slayer: Kimetsu no Yaiba Infinity Castle,2025-07-18,8.796,2225
3,The Shawshank Redemption,1994-09-23,8.731,31473
4,The Godfather,1972-03-14,8.688,23675
5,Project Hail Mary,2026-03-15,8.642,8088
6,Michael,2026-04-22,8.625,4459
7,12 Angry Men,1957-04-10,8.574,10424
8,The Godfather Part II,1974-12-20,8.573,14401
9,Schindler's List,1993-12-15,8.569,17982